# Generated by Django 3.2.13 on 2022-06-21 13:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Please enter valid name', regex='^([A-Za-z]{3,})( [a-z]+)*( [a-z]+)*$')])),
                ('gender_type', models.CharField(choices=[('1', 'male'), ('2', 'female'), ('3', 'others')], max_length=1)),
                ('dob', models.DateField()),
                ('relation_type', models.CharField(choices=[('1', 'mother'), ('2', 'father'), ('3', 'wife'), ('4', 'first_child'), ('5', 'second_child')], max_length=1)),
                ('aadhar_number', models.BigIntegerField(unique=True)),
                ('created_date', models.DateField(auto_now=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
