# Generated by Django 3.2.13 on 2022-06-15 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturing_company', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('manufacturing_year', models.DateField()),
                ('chase_number', models.CharField(max_length=20, unique=True)),
                ('created_by', models.DateField(auto_now=True)),
                ('updated_by', models.DateField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
