# Generated by Django 4.0.4 on 2022-05-19 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_amount', models.IntegerField()),
                ('claimed_amount', models.IntegerField()),
                ('claimed_date', models.DateField(auto_now=True)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.insurance')),
            ],
        ),
    ]
