# Generated by Django 3.2.13 on 2022-06-21 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_amount', models.IntegerField()),
                ('claimed_amount', models.IntegerField()),
                ('remaining_insurance_amount', models.IntegerField()),
                ('claimed_date', models.DateField(auto_now=True)),
                ('claimed_by', models.CharField(max_length=50)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.insurance')),
            ],
        ),
    ]
