# Generated by Django 3.2.13 on 2022-06-08 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance_company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('policy_type', models.CharField(choices=[('1', 'health'), ('2', 'bike'), ('3', 'car')], max_length=1)),
                ('min_policy_amount', models.IntegerField()),
                ('max_policy_amount', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('created_date', models.DateField(auto_now=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_company.company')),
            ],
        ),
    ]
