# Generated by Django 3.2.13 on 2022-06-08 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('policy', '0001_initial'),
        ('property', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_number', models.CharField(max_length=20, unique=True)),
                ('holder_name', models.CharField(max_length=50)),
                ('insurance_type', models.CharField(choices=[('1', 'self'), ('2', 'term'), ('3', 'individual')], max_length=1)),
                ('insurance_amount', models.IntegerField()),
                ('remaining_amount', models.IntegerField()),
                ('start_date', models.DateField(auto_now=True)),
                ('renewal_date', models.DateField()),
                ('remaining_days', models.IntegerField(null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='policy.policy')),
                ('property', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
    ]
