# Generated by Django 3.2.13 on 2022-06-08 12:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('name', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Please enter valid name', regex='^([A-Za-z]{3,})( [a-z]+)*( [a-z]+)*$')])),
                ('gender_type', models.CharField(choices=[('1', 'male'), ('2', 'female'), ('3', 'others')], max_length=1)),
                ('dob', models.DateField()),
                ('mobile_number', models.BigIntegerField(unique=True, validators=[django.core.validators.RegexValidator(code='invalid_number', message='Phone number must be 10 digits and starts with either(6,7,8,9)', regex='^[6789]\\d{9}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('aadhar_number', models.BigIntegerField()),
                ('current_project', models.CharField(max_length=50)),
                ('joining_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
    ]
