# Generated by Django 4.0.4 on 2022-05-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('dob', models.DateField()),
                ('mobile_number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('created_date', models.DateField()),
                ('updated_date', models.DateField()),
            ],
        ),
    ]
