# Generated by Django 4.0.4 on 2022-05-23 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('dob', models.DateField()),
                ('mobile_number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('current_project', models.CharField(max_length=50)),
                ('joining_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateField()),
                ('updated_date', models.DateField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
    ]
