# Generated by Django 4.0.4 on 2022-05-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BigIntegerField(default=True),
        ),
    ]
